apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  annotations:
    sonataflow.org/description: Target Workflow for the pooling events
    sonataflow.org/expressionLang: jq
    sonataflow.org/profile: dev
    sonataflow.org/version: "1.0"
  creationTimestamp: null
  labels:
    app: target-workflow
    sonataflow.org/workflow-app: target-workflow
  name: target-workflow
  namespace: default
spec:
  flow:
    events:
    - dataOnly: true
      kind: consumed
      name: fromPooling
      source: urn:camel-pooling
      type: org.acme.sw.camel.pooling
    functions:
    - name: log
      operation: sysout:INFO
      type: custom
    start:
      stateName: ListenEvent
    states:
    - end:
        terminate: true
      exclusive: true
      name: ListenEvent
      onEvents:
      - actionMode: sequential
        actions:
        - actionDataFilter:
            useResults: true
          functionRef:
            arguments:
              message: ${ "The name is \(.profile.name)" }
            invoke: sync
            refName: log
          name: logEvent
        eventDataFilter:
          useData: true
        eventRefs:
        - fromPooling
      type: event
  podTemplate:
    container:
      resources: {}
  resources: {}
status:
  address: {}
  lastTimeRecoverAttempt: null
